# inherit_from: .rubocop_todo.yml

Lint/RescueWithoutErrorClass:
  Exclude:
    - 'app/models/resume.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false